apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-ai-tasks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manish7398/AI-Task-Processing-Platform-.git
    targetRevision: mern-infra
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mern-ai-tasks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m