apiVersion: v1
kind: Secret
metadata:
  name: mern-secret
  namespace: mern-ai-tasks
type: Opaque
stringData:
  JWT_SECRET: mysupersecretkeybrooooooooooos
  MONGODB_URI: mongodb://vikki:.345abc..1@ac-ntrgsov-shard-00-00.rtg9hsz.mongodb.net:27017,ac-ntrgsov-shard-00-01.rtg9hsz.mongodb.net:27017,ac-ntrgsov-shard-00-02.rtg9hsz.mongodb.net:27017/heloooooo?ssl=true&replicaSet=atlas-oa0jlz-shard-0&authSource=admin&appName=kyaa